image: 'kavatech/healthd:0.1.4'
ca: '' #base64 encoded string
crt: '' #base64 encoded string
key: '' #base64 encoded string
hosts: []
ingressClass: 'nginx'
affinity: {}

etcd:
  statefulset:
    replicaCount: 3

  persistence:
    enabled: false