image: 'kavatech/healthd:0.1.3'
ca: '' #base64 encoded string
crt: '' #base64 encoded string
key: '' #base64 encoded string
hosts: []
ingressClass: 'nginx'
affinity: {}

etcd:
  persistentVolume:
    enabled: false

  affinity: {}