apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: healthd
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
  - hosts:
    {{- range .Values.hosts }}
    - '{{ . }}'
    {{- end }}
    secretName: healthd-ing-secret
  rules:
  {{- range .Values.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: healthd
          servicePort: 443
  {{- end }}